site_name: ASL Trunk Robot
site_description: ASL Trunk Robot documentation
site_url: https://stanfordasl.github.io/trunk-stack

repo_url: https://github.com/StanfordASL/trunk-stack
repo_name: StanfordASL/trunk-stack

theme:
  name: material
  favicon: assets/favicon-robot.png
  logo: assets/asl-white.png
  palette:
    primary: custom
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md
  - Design: 
    - Mechanical: mechanical_design.md 
    - Electrical: electrical_design.md 
    - Software: software_design.md 
  - Setup:
    - 3D Printing: 3dprinting.md 
    - OpiTrack System: optitrack.md 
  - Usage:
    - Motion Capture: mocap.md
    - Motor Control: motor_control.md
    - Collecting data: collecting_data.md
    - Video Streaming: video_streaming.md
    - Telemetry Viewer: telemetry_viewer.md
    - Teleoperation: teleoperation.md
    - Visuomotor Rollout: visuomotor_rollout.md
  - Contributing: contributing.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - git-committers:
      repository: StanfordASL/trunk-stack
      branch: main
  - git-revision-date-localized
